logging:
  level:
    root: INFO
    io.kyungseo: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "[user-service,%X{traceId},%X{spanId},%X{X-Correlation-ID}] %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
